blank_issues_enabled: true
contact_links:
  - name: PropGeo Community Support
    url: https://propgeo.com/slack/
    about: Please ask and answer questions here.
  - name: PropGeo Documenation Issues
    url: https://github.com/propgeo/propgeo.github.io/issues
    about: Please documenation related issues here.
 
